### ISSUE TITLE
Crash when using Chorus Warps and Console Expeience

### ISSUE THREAD

**Issue by Wedge1453** [freeeranger/choruswarps#3]
https://github.com/Pepperoni-Jabroni/ChorusLinks/files/6104285/crash-2021-03-08_20.40.00-client.txt

**Comment by freeeranger** [comment]
Seems like the mods are incompatible since console experience does stuff to the tooltip system, hop onto my discord server and I'll try to help you recover your world.

**Comment by Fuzss** [comment]
Hi, so my mod creates all the tooltip parts (name, information, enchantments, ...) separately (for customization purposes) and then combines them afterwards.

Your Golden Chorus Fruit doesn't seem to like that, it expects the tooltip list to at least contain one entry, which isn't the case here as no information has been added yet.

[This](https://github.com/freerangerstudios/choruswarps/blob/ad32259296ce903ad17e29722bd861d6da9a9480/src/main/java/com/freeranger/choruswarps/items/GoldenChorusFruitItem.java#L162) and [this](https://github.com/freerangerstudios/choruswarps/blob/ad32259296ce903ad17e29722bd861d6da9a9480/src/main/java/com/freeranger/choruswarps/items/GoldenChorusFruitItem.java#L167) seem to be the relevant lines of code that would need changing. So maybe you could call List::add without specifying an index? Since the list size is not greater than one anyways in that case it wouldn't change any behavior.

If I don't forget I'll also add something to Console Experience for catching this kind of exception, in case another mod makes the same assumptions.

**Comment by freeeranger** [comment]
Yeah that should probably fix it, I'll download your mod and test the mods together in my dev environment to see if it works :)

**Comment by freeeranger** [comment]
This issue should now be fixed (at least according to my testing) and the new file is being uploaded to curseforge right now. Thanks for reporting!

**Comment by Fuzss** [comment]
Thank you!
